const type = {
    SET_CURRENT_TOKEN0: 'SET_CURRENT_TOKEN0',
    SET_CURRENT_TOKEN1: 'SET_CURRENT_TOKEN1',
    SET_CURRENT_MODE: 'SET_CURRENT_MODE',
    SET_PAIR_TOKENS: 'SET_PAIR_TOKENS',
    SET_ETH_PRICE: 'SET_ETH_PRICE',
    SET_GAS_FEE_OPTIONS: 'SET_GAS_FEE_OPTIONS',
}

export default type;